# Generated by Django 4.2.8 on 2024-01-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_customer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
