# Generated by Django 4.2.8 on 2024-01-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_users_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
