# Generated by Django 4.2.8 on 2024-01-04 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deadline', models.DateField()),
                ('Expected_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Description', models.CharField(max_length=255)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
