# Generated by Django 4.2.8 on 2024-01-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderRequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='Document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='Description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='Expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
