# Generated by Django 4.2.8 on 2024-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderRequest', '0002_orderrequest_document_alter_orderrequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
