# Generated by Django 4.2.8 on 2024-01-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderRequest', '0003_alter_orderrequest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
