# Generated by Django 4.2.8 on 2024-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderRequest', '0005_remove_orderrequest_date_orderrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='Status',
            field=models.CharField(blank=True, default='Lead', max_length=200, null=True),
        ),
    ]
