# Generated by Django 4.2.8 on 2024-01-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderRequest', '0006_orderrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='Status',
            field=models.CharField(blank=True, default='New', max_length=200, null=True),
        ),
    ]
